# Generated by Django 4.2.7 on 2023-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "rollno",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("regno", models.CharField(max_length=20)),
                ("cgpa", models.CharField(blank=True, max_length=10, null=True)),
                ("dept", models.CharField(max_length=100)),
            ],
        ),
    ]
